version: "3"

services:
  app:
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: osrm-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./profiles:/opt
    environment:
      - OSRM_ALGORITHM=mld
      - OSRM_THREADS=2
      - OSRM_PORT=5000
      - OSRM_PROFILE=/opt/foot.lua
      - OSRM_MAP_NAME=uruguay
      - OSRM_GEOFABRIK_PATH=south-america/uruguay-latest.osm.pbf